# Generated by Django 3.1.4 on 2021-01-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
