# Generated by Django 3.1.4 on 2021-01-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210125_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='ip_address',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='session_id',
            new_name='web',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='interest',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='mobile',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
