# Generated by Django 3.1.4 on 2021-02-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210127_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='web',
            new_name='budget',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='app_type',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
